import argparse
parser = argparse.ArgumentParser()
parser.add_argument('--parameter',  default='GIE_MODEL', help='name of parameter file')
parser.add_argument('--epoch', type=int, default=100, help='epoch number')
parser.add_argument('--lr', type=float, default=1e-4, help='learning rate')
parser.add_argument('--batchsize', type=int, default=16, help='training batch size')
parser.add_argument('--trainsize', type=int, default=352, help='training dataset size')
parser.add_argument('--clip', type=float, default=0.5, help='gradient clipping margin')
parser.add_argument('--decay_rate', type=float, default=0.1, help='decay rate of learning rate')
parser.add_argument('--decay_epoch', type=int, default=45, help='every n epochs decay learning rate')
parser.add_argument('--load', type=str, default=None, help='train from checkpoints')
parser.add_argument('--gpu_id', type=str, default='4', help='train use gpu')

parser.add_argument('--rgb_root', type=str, default='Dataset/VT5000/VT5000_clear/Train/RGB/', help='the training rgb images root')
parser.add_argument('--t_root', type=str, default='Dataset/VT5000/VT5000_clear/Train/T/', help='the training t images root')
parser.add_argument('--gt_root', type=str, default='Dataset/VT5000/VT5000_clear/Train/GT/', help='the training gt images root')
parser.add_argument('--save_path', type=str, default='the_ans/', help='the path to save models and logs')
opt = parser.parse_args()
